user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_listpage:
    path:     /users/{pageId}
    defaults: { _controller: UserBundle:User:index }
    requirements:
        pageId:  \d+

user_newuserpage:
    path:     /users/new
    defaults: { _controller: UserBundle:User:new }
user_editpage:
    path:     /users/edit/{id}
    defaults: { _controller: UserBundle:User:edit }
    requirements:
        id:  \d+

user_viewpage:
    path:     /users/view/{id}
    defaults: { _controller: UserBundle:User:view }
    requirements:
        id:  \d+
